apiVersion: v1
kind: ConfigMap

metadata:
  name: note-config

data:
  MONGO_URI: 'mongodb+srv://harsh321:harsh@cluster0.ic5ngw0.mongodb.net/notes-db?retryWrites=true&w=majority'
  PORT: "5000"
  NODE_ENV: production
  APP_NAME: note-app