apiVersion: apps/v1
kind: Deployment

metadata:
  name: note-app
  labels:
    first: app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
        - name: my-note
          image: harsh0soni/self:v1.0.0

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: note-config

---
apiVersion: v1
kind: Service

metadata:
  name: notes-service

spec:
  selector:
    app: web

  ports:
    - protocol: TCP
      port: 5200
      targetPort: 5000

  type: NodePort